module.exports = {
  ID: { value: "" },
  Type: { value: "simple" },
  SKU: "sku",
  Name: "name",
  Published: { value: 1 },
  "Is featured?": { value: 0 },
  "Visibility in catalog": { value: "visible" },
  "Short description": { value: "" },
  Description: "short_description",
  "Date sale price starts": { value: "" },
  "Date sale price ends": { value: "" },
  "Tax status": { value: "taxable" },
  "Tax class": { value: "" },
  "In stock?": { value: 1 },
  Stock: { value: "" },
  "Low stock amount": { value: "" },
  "Backorders allowed?": { value: 0 },
  "Sold individually?": { value: 0 },
  "Weight(kg)": { value: "" },
  "Length(cm)": { value: "" },
  "Width(cm)": { value: "" },
  "Height(cm)": { value: "" },
  "Allow customer reviews?": { value: 1 },
  "Purchase note": { value: "" },
  "Sale price": "discount",
  "Regular price": "price",
  Categories: "brand_name",
  Tags: { value: "" },
  "Shipping class": { value: "" },
  Images: "thumbnail_url",
  "Download limit": { value: "" },
  "Download expiry days": { value: "" },
  Parent: { value: "" },
  "Grouped products": { value: "" },
  Upsells: { value: "" },
  "Cross-sells": { value: "" },
  "External URL": { value: "" },
  "Button text": { value: "" },
  Position: { value: 0 },
};
